FROM golang

RUN ["go", "get", "github.com/codegangsta/gin"]

VOLUME ["/go/src/github.com/tobyjsullivan/event-history"]

EXPOSE 3000

WORKDIR /go/src/github.com/tobyjsullivan/event-history

CMD ["gin"]

